FROM  rabbitmq:3-management
MAINTAINER Jared Atkinson <jared@invoke-ir.com>
RUN \
    apt-get update -y \
    && apt-get upgrade -y \
    && apt-get dist-upgrade -y \
    && apt-get install -y python2.7 python-pip \
    && pip install pika requests
ADD ace.py /root/ace.py
CMD \
    /usr/local/bin/docker-entrypoint.sh rabbitmq-server & \
    sleep 30 \
    && python /root/ace.py -s 127.0.0.1 -u $RABBITMQ_DEFAULT_USER -p $RABBITMQ_DEFAULT_PASS